<?php
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20261002000100 extends AbstractMigration
{
    public function getDescription(): string { return 'Initial local restaurant ledger with integer centimes and bounded quantities.'; }
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(180) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL)');
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, phone VARCHAR(40) NOT NULL)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, price_cents INT NOT NULL CHECK (price_cents >= 0 AND price_cents <= 100000000))');
        $this->addSql('CREATE TABLE delivery (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id INT NOT NULL REFERENCES client(id), date DATE NOT NULL)');
        $this->addSql('CREATE INDEX delivery_client_date ON delivery (client_id, date)');
        $this->addSql('CREATE TABLE delivery_line (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id INT NOT NULL REFERENCES delivery(id), product_id INT NOT NULL REFERENCES product(id), product_name VARCHAR(120) NOT NULL, quantity INT NOT NULL CHECK (quantity > 0 AND quantity <= 100000), unit_price_cents INT NOT NULL CHECK (unit_price_cents >= 0 AND unit_price_cents <= 100000000))');
        $this->addSql('CREATE INDEX IDX_887C6C12136921 ON delivery_line (delivery_id)');
        $this->addSql('CREATE TABLE line_return (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, line_id INT NOT NULL REFERENCES delivery_line(id), date DATE NOT NULL, quantity INT NOT NULL CHECK (quantity > 0 AND quantity <= 100000))');
        $this->addSql('CREATE INDEX IDX_D3D069B24D7B7542 ON line_return (line_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id INT NOT NULL REFERENCES client(id), date DATE NOT NULL, amount_cents INT NOT NULL CHECK (amount_cents > 0 AND amount_cents <= 100000000), note VARCHAR(200) NOT NULL)');
        $this->addSql('CREATE INDEX payment_client_date ON payment (client_id, date)');
    }
    public function down(Schema $schema): void
    {
        foreach (['payment', 'line_return', 'delivery_line', 'delivery', 'product', 'client', 'admin'] as $table) { $this->addSql('DROP TABLE '.$table); }
    }
}
