<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004000400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Reusable catalogue articles, compositions and supplier offers.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE product ADD code VARCHAR(100) DEFAULT NULL, ADD kind VARCHAR(20) NOT NULL DEFAULT 'dish', ADD category VARCHAR(120) NOT NULL DEFAULT '', ADD aliases JSON NOT NULL DEFAULT '[]', ADD unit VARCHAR(10) NOT NULL DEFAULT 'PORTION', ADD sellable BOOLEAN NOT NULL DEFAULT TRUE, ADD for_delivery BOOLEAN NOT NULL DEFAULT TRUE, ADD active BOOLEAN NOT NULL DEFAULT TRUE, ADD notes TEXT NOT NULL DEFAULT '', ADD recipe_output_quantity NUMERIC(18,6) DEFAULT NULL, ADD recipe_complete BOOLEAN NOT NULL DEFAULT FALSE, ADD recipe_notes TEXT NOT NULL DEFAULT '', ADD source JSON NOT NULL DEFAULT '[]'");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD77153098 ON product (code)');
        $this->addSql("ALTER TABLE product ADD CONSTRAINT product_kind CHECK (kind IN ('dish','ingredient','preparation','packaging')), ADD CONSTRAINT product_unit CHECK (unit IN ('KG','L','PC','PORTION')), ADD CONSTRAINT product_output CHECK (recipe_output_quantity IS NULL OR recipe_output_quantity > 0)");
        $this->addSql("CREATE TABLE recipe_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_id INT NOT NULL REFERENCES product(id) ON DELETE CASCADE, component_id INT NOT NULL REFERENCES product(id), quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0), unit VARCHAR(10) NOT NULL CHECK (unit IN ('KG','L','PC','PORTION')), quantity_basis VARCHAR(10) NOT NULL CHECK (quantity_basis IN ('raw','usable')), notes TEXT NOT NULL, position INT NOT NULL, PRIMARY KEY(id), CONSTRAINT recipe_no_self CHECK (parent_id <> component_id))");
        $this->addSql('CREATE INDEX IDX_RECIPE_PARENT ON recipe_line (parent_id)');
        $this->addSql('CREATE INDEX IDX_RECIPE_COMPONENT ON recipe_line (component_id)');
        $this->addSql("CREATE TABLE purchase_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL REFERENCES product(id) ON DELETE CASCADE, supplier_id INT NOT NULL REFERENCES supplier(id), price_cents INT NOT NULL CHECK (price_cents >= 0), quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0), unit VARCHAR(10) NOT NULL CHECK (unit IN ('KG','L','PC','PORTION')), usable_yield NUMERIC(18,6) NOT NULL CHECK (usable_yield > 0 AND usable_yield <= 1), preferred BOOLEAN NOT NULL, notes TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_OFFER_PRODUCT ON purchase_offer (product_id)');
        $this->addSql('CREATE INDEX IDX_OFFER_SUPPLIER ON purchase_offer (supplier_id)');
        $this->addSql('CREATE UNIQUE INDEX purchase_offer_preferred ON purchase_offer (product_id) WHERE preferred = TRUE');

        foreach (['recipe_line', 'purchase_offer'] as $table) {
            $this->addSql('ALTER TABLE public.'.$table.' ENABLE ROW LEVEL SECURITY');
            $this->addSql('REVOKE ALL ON TABLE public.'.$table.' FROM PUBLIC');
            $this->addSql(<<<SQL
DO \$\$
DECLARE api_role text; identity_sequence text := pg_get_serial_sequence('public.$table', 'id');
BEGIN
    EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM PUBLIC', identity_sequence);
    FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON TABLE public.$table FROM %I', api_role);
            EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM %I', identity_sequence, api_role);
        END IF;
    END LOOP;
END
\$\$
SQL);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE recipe_line');
        $this->addSql('DROP TABLE purchase_offer');
        $this->addSql('DROP INDEX UNIQ_D34A04AD77153098');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT product_kind, DROP CONSTRAINT product_unit, DROP CONSTRAINT product_output, DROP code, DROP kind, DROP category, DROP aliases, DROP unit, DROP sellable, DROP for_delivery, DROP active, DROP notes, DROP recipe_output_quantity, DROP recipe_complete, DROP recipe_notes, DROP source');
    }
}
