<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Suppliers and immutable human-validated purchase documents; no stored photos.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(180) NOT NULL, aliases JSON NOT NULL, reporting_label VARCHAR(180) NOT NULL)');
        $this->addSql("CREATE TABLE supplier_invoice (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id INT NOT NULL REFERENCES supplier(id), supplier_name VARCHAR(180) NOT NULL, reporting_label VARCHAR(180) NOT NULL, date DATE NOT NULL, reference VARCHAR(180) NOT NULL, reference_key VARCHAR(180) NOT NULL, document_kind VARCHAR(20) NOT NULL CHECK (document_kind IN ('invoice', 'delivery_note')), total_cents INT NOT NULL CHECK (total_cents > 0 AND total_cents <= 100000000), validated_by INT NOT NULL REFERENCES admin(id), validated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, provenance VARCHAR(20) NOT NULL CHECK (provenance IN ('manual', 'extracted', 'corrected')), extraction JSON DEFAULT NULL, draft_token VARCHAR(64) NOT NULL UNIQUE, UNIQUE (supplier_id, reference_key, document_kind))");
        $this->addSql('CREATE INDEX supplier_invoice_date ON supplier_invoice(date, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE supplier_invoice');
        $this->addSql('DROP TABLE supplier');
    }
}
